FROM node:26-alpine3.22
WORKDIR /app/
COPY src/ ./src
COPY public ./public
COPY index.html ./
COPY package.json package-lock.json tsconfig.json .prettierrc ./
RUN npm install
EXPOSE 5173
CMD [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]